### ISSUE TITLE
Kerbals with EVA chairs seem to be in front of everything

### ISSUE THREAD

**Issue by likeproblem** [LGhassen/Deferred#43]
![screenshot24](https://github.com/user-attachments/assets/4159e1f5-e6bf-4dd8-9850-d73d9cc0b2d0)
Seems normal
![screenshot25](https://github.com/user-attachments/assets/48e505b4-801a-4ea8-a062-3dc9e6b8fc1b)
![screenshot26](https://github.com/user-attachments/assets/80f67ef2-b568-43ef-a71c-1d8c80ed6989)
"hmm yes lets defy laws of reality"
![screenshot27](https://github.com/user-attachments/assets/5779b77e-6096-45ab-be04-71e27d6b3923)
apparently EVA kerbals dont suffer from that

[KSP.zip](https://github.com/user-attachments/files/17051411/KSP.zip)
ksp.log

**Comment by LGhassen** [comment]
Working correctly on my end on the latest version as you can see here

https://i.imgur.com/tO1bsbG.jpeg

https://i.imgur.com/mhLJB4W.png

https://i.imgur.com/UqQphIY.png

I looked at your logs and saw some errors due to other mods but didn't notice anything that could be related. Try to reproduce this on just a minimal install, I suspect it's caused by another mod. If I can't reproduce it on my side I can't fix it.

**Comment by LGhassen** [comment]
Closed for not being reproducible
