### ISSUE TITLE
Issues with TUFX Ambient Occlusion in IVA mode

### ISSUE THREAD

**Issue by JonnyOThan** [LGhassen/Deferred#47]
The default TUFX AO settings show artifacts in IVA mode with deferred along the edges of the windows/depth masks:

![image](https://github.com/user-attachments/assets/f1f3e312-0221-4773-a20e-f39ab447f59f)

This isn't terribly surprising since the depth mask isn't really any different from opaque geo - can a stencil fix that?

This artifact goes away with ScalableAmbientObscurance, but in fact that mode seems to not work at all unless "Ambient only" is turned off:

intensity 0.5:
![image](https://github.com/user-attachments/assets/7f7ff6e2-63bf-4ca8-bb8a-f8cd2de5084c)

intensity 10:
![image](https://github.com/user-attachments/assets/2b7278f1-c8fc-4dcd-ab56-a1feb9167064)

Only some of the emissives are affected (navball, lit buttons).

With ambient only off:
![image](https://github.com/user-attachments/assets/248a1098-4574-4a33-9f08-e8a855101f10)

So that last image really shows the problem: the high-frequency block of switches in the lower center of the screen and the overhang above the navball have relatively lower AO intensity than other parts of the cockpit.  Normally these are the areas that should have the strongest shadowing.

Well this is interesting....if I play with the "radius" field it gets closer to what I'd expect but it almost seems to control a direction:
![image](https://github.com/user-attachments/assets/103543f0-6166-4989-bfc7-9accc2454663)

**Comment by LGhassen** [comment]
Is this with the new FreeIVA depthmasks we discussed last time?

Stencil cannot fix this because Unity doesn't actually give control over the background stencil bit (only a few stencil bits are actually exposed to custom shaders).

You could get around this by checking the alpha channel of the emission texture (_CameraGBufferTexture3) which is set to 0 if nothing opaque rendered (excluding depth masks) and set to 1 if something opaque rendered. I do this here for depthMasks in the lighting pass https://github.com/LGhassen/Deferred/commit/ed34eba4297e511bc0b02a23976c94a71f71a73b#diff-9acef8ad85e71784189f9f00996bcad4126522229d84d6d64647b77bcf43aeabR140

You'll have to add this in the AO shaders. I'm not sure if this will work in HDR or not, you could take a renderdoc capture with HDR on/off and check if that channel is set to the expected values before doing any work.

**Comment by JonnyOThan** [comment]
Yeah, this is the current public build of FreeIva with the additional depth mask material on the window.

I'm kind of less concerned about the window than the other stuff. It's actually hard to get the switches and things to behave like they should (the last picture is closer).  I'm wondering if the "ambient only" flag isn't working properly with deferred or if something else is going weird about how the whole thing works.

**Comment by LGhassen** [comment]
I'm really not sure what you mean, the buttons not looking right seems more of a config issue for the radius/intensity.

I'm not sure what the "ambient only" flag does, but by default in the older tufx version and using deferred the AO works correctly in that it only writes the AO to the AO channel (alpha channel of _CameraGBufferTexture0) and that's correctly integrated in the lighting and not just used as a darkening filter over the screen.

Not sure what may have changed since then but I'll retest with the new tufx and freeIVA. Now that I think about it, in the above screens you posted it doesn't look like deferred is installed or working, or maybe that's because I never use without scatterer, not sure. Can you use deferred's debug mode and look at the occlusion mode?

**Comment by JonnyOThan** [comment]
MSVO, ambient only.  There's no visible AO.
![image](https://github.com/user-attachments/assets/f0d816b8-a383-42eb-a8a9-9a351423d5bd)
occlusion:
![image](https://github.com/user-attachments/assets/b30d1325-aed2-47d4-bfb2-432a4ea9cd2f)
ambient (maybe this is the problem?):
![image](https://github.com/user-attachments/assets/83d56851-419f-4a7d-913b-d1cfbdf9a3f1)

ambient only = false (this looks a lot closer to correct):
![image](https://github.com/user-attachments/assets/3a7460de-dcdd-4f6c-a7d6-e65b83d88118)
![image](https://github.com/user-attachments/assets/4faad901-1365-4fec-a2a2-74967e588891)
![image](https://github.com/user-attachments/assets/1940dc8c-e13d-467c-a3e8-108a12e0076f)

**Comment by LGhassen** [comment]
Ok yeah the issue might be is that the ambient lighting is completely absent, but why would that be?
Do you have reflection probe enabled and can you check reflection probe debug mode in deferred?
Also interestingly I never used the "Ambient Only" mode in TUFX but it always seemed to work in that way, so I assume that's default if you don't enable the checkbox?

**Comment by JonnyOThan** [comment]
Reflection probe is enabled (that would have been embarrassing).

Yes, "ambient only = true" is the default if the setting doesn't have an override.

I am on the debug build though, and the ambient in external view is also basically black...

![image](https://github.com/user-attachments/assets/048c7db9-7677-489e-b3c0-e2963d0e6187)

**Comment by LGhassen** [comment]
I tested on the debug build recently and didn't run into any issues. Does this work with scatterer installed but not in stock?

Can you include your KSP.log and it it's not too mcuh trouble a renderdoc capture?

**Comment by JonnyOThan** [comment]
ok yeah this is looking way better.  Sorry!
using SAO instead of MSVO in IVA mode looks good!
![image](https://github.com/user-attachments/assets/39e3508f-7057-4041-8e9a-aec7b5499785)


![image](https://github.com/user-attachments/assets/2569e049-4683-4497-a697-fbb2f5cfa74a)
