### ISSUE TITLE
Visually conflicts with built-in ambient light boost

### ISSUE THREAD

**Issue by videopilot** [LGhassen/Deferred#50]
If the built-in ambient boost is greater than zero, there is a  noticeable edge between the ambient lit part of a vessel (built-in ambient) and the part lit by a nearby planet (deferred). To me, it looks like if I were to take images made with either and in Photoshop combine them with the lighter color blending mode, when I'd think it really it should just be adding the deferred ambient to the built-in ambient. See images...

![Screenshot 2024-11-08 at 5 45 25 AM](https://github.com/user-attachments/assets/14ff44cd-3655-4b19-8742-e7d70fd41523)

Different ambient boost settings...

![ambient](https://github.com/user-attachments/assets/20a876c7-59bf-43de-b3c4-9cd529d767ce)

![Screenshot 2024-11-08 at 5 55 49 AM](https://github.com/user-attachments/assets/fb25dc40-64ce-4b18-8dc5-bbe338b81434)

I know the compatibility with PlanetShine is “obsolete at default settings” and it does look great and allow additional tweaking, but at non-default settings (I.e. with ambient boost), this issue persists.

**Comment by LGhassen** [comment]
That's more or less normal because I'm not adding the built-in "fake" ambient and deferred's "real" ambient, I'm just falling back to the fake ambient if deferred's ambient falls below the brightness threshold of the fake ambient, which is for gameplay/visibility reasons.

I could make them add to each other instead but I found that it washes out the image and doesn't look as good. I don't really intend for the fake ambient or fake ambient boosts to be used more than this as imo they wash out the image and aren't the right solution to the problem (imo eye adaptation like with TUFX is a better solution) so I don't really plan to support this.

**Comment by LGhassen** [comment]
It doesn't look the same with ambient boost at zero (if that means the default ambient light which is non zero). Max(ambient, deferredAmbient) !=  ambient + deferredAmbient.

Ok yeah on Mac TUFX doesn't work. I don't know I guess feel free to make a pull request that makes them add to each other if ambient boost is enabled but keeps the current behaviour if its disabled.
